"""
============================================================
Project : DNS Measurement Platform
Module  : sqlite_schema.py

Description
-----------
Creates SQLite archive database tables.

SQLite is used as the Archive Database.

It stores complete normalized Observation records, but it is
not responsible for telemetry, dashboard, or analytics.

Author
------
Helen Liu
============================================================
"""

import json
from sqlite3 import Connection

from app.database.sqlite_connection import get_connection, close_connection


def create_tables(connection: Connection) -> None:
    """
    Create all archive database tables.
    """

    create_measurement_table(connection)
    create_probe_table(connection)
    create_observation_table(connection)

    connection.commit()


def create_measurement_table(connection: Connection) -> None:
    """
    Store RIPE Atlas measurement metadata.

    One measurement_id should appear only once.
    """

    cursor = connection.cursor()

    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS measurement (
            measurement_id INTEGER PRIMARY KEY,
            description TEXT,
            target TEXT,
            interval_seconds INTEGER,
            protocol TEXT,
            address_family INTEGER,
            start_time INTEGER,
            stop_time INTEGER,
            raw_json TEXT
        );
        """
    )


def create_probe_table(connection: Connection) -> None:
    """
    Store RIPE Atlas probe metadata.

    Probe information is stored separately because many
    observations can be generated by the same probe.
    """

    cursor = connection.cursor()

    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS probe (
            probe_id INTEGER PRIMARY KEY,
            asn_v4 INTEGER,
            asn_v6 INTEGER,
            country_code TEXT,
            latitude REAL,
            longitude REAL,
            description TEXT,
            address_v4 TEXT,
            address_v6 TEXT,
            prefix_v4 TEXT,
            prefix_v6 TEXT,
            first_connected INTEGER,
            status_name TEXT,
            raw_json TEXT
        );
        """
    )


def create_observation_table(connection: Connection) -> None:
    """
    Store complete normalized Observation records.

    SQLite stores Observation as archive data.

    JSON sections are stored as TEXT so the full Observation
    structure can be preserved without flattening every field
    into database columns.
    """

    cursor = connection.cursor()

    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS observation (
            observation_id TEXT PRIMARY KEY,

            measurement_id INTEGER,
            probe_id INTEGER,

            timestamp INTEGER,
            stored_timestamp INTEGER,
            observation_type TEXT,

            identity TEXT,
            metadata TEXT,
            network TEXT,
            address_family TEXT,
            location TEXT,
            protocol TEXT,
            routing TEXT,
            path TEXT,
            telemetry TEXT,

            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

            FOREIGN KEY (measurement_id)
                REFERENCES measurement(measurement_id),

            FOREIGN KEY (probe_id)
                REFERENCES probe(probe_id)
        );
        """
    )


def drop_tables(connection: Connection) -> None:
    """
    Drop all archive tables.

    Use only during development.
    """

    cursor = connection.cursor()

    cursor.execute("DROP TABLE IF EXISTS observation;")
    cursor.execute("DROP TABLE IF EXISTS probe;")
    cursor.execute("DROP TABLE IF EXISTS measurement;")

    connection.commit()


def reset_database() -> None:
    """
    Drop and recreate all tables.
    """

    connection = get_connection()

    try:
        drop_tables(connection)
        create_tables(connection)

    finally:
        close_connection(connection)


def initialize_database() -> None:
    """
    Create archive database tables if they do not exist.
    """

    connection = get_connection()

    try:
        create_tables(connection)

    finally:
        close_connection(connection)


if __name__ == "__main__":
    initialize_database()
    print("SQLite schema initialized.")