"""
============================================================
Project : DNS Measurement Platform
Module  : observation.py

Description
-----------
Defines the Canonical Observation Framework used by the
Network Telemetry Platform.

Observation represents one complete normalized network
observation collected from a supported data source.

The framework combines information derived from:

    - Measurement metadata
    - Probe metadata
    - Runtime result data
    - Platform collection metadata

Observation is shared by:

    - Parser
    - Validator
    - Normalizer
    - SQLite Archive
    - Telemetry Builder
    - InfluxDB Writer
    - Prometheus Exporter
    - Grafana
    - JavaScript Platform Interface
    - Analytics Engine
    - AI Insight

The Collector Layer does not create Observation objects.

Collector modules only download and preserve original
source data.

The Normalization Layer reads collected source data and
converts it into the Canonical Observation Framework.

Design Philosophy
-----------------
Observation is the canonical platform data model.

Observation must not depend directly on:

    - RIPE Atlas
    - SQLite
    - InfluxDB
    - Prometheus
    - Grafana
    - JavaScript
    - Any storage implementation
    - Any telemetry backend

The normalization flow is:

    Raw Source Data
        -> Parser
        -> Validator
        -> Normalizer
        -> Observation
        -> SQLite Archive

Telemetry generation follows:

    Observation
        -> Go Telemetry Builder
        -> Metric Model
        -> InfluxDB Writer
        -> Prometheus Exporter
        -> Grafana

Observation contains the following top-level sections:

    - identity
    - metadata
    - measurement
    - probe
    - network
    - location
    - protocol
    - routing
    - path
    - status
    - telemetry

Measurement and Probe metadata are distributed according
to engineering meaning.

Examples:

    Probe geographic information
        -> location

    Probe ASN and prefix information
        -> routing.bgp.source

    Measurement target ASN and prefix information
        -> routing.bgp.destination

    Runtime DNS packet information
        -> protocol.dns

    Runtime transaction information
        -> network

Protocol-specific payloads are normalized by the Protocol Framework.

Each Observation stores a protocol-agnostic Protocol object:

    protocol
        ├── name
        ├── display_name
        ├── family
        ├── version
        └── decoded

The decoded object is produced by the registered protocol
decoder and contains protocol-specific fields.

Analytics may correlate multiple Observation types, for
example:

    DNS + BGP
    DNS + Traceroute
    DNS + Streaming Telemetry
    BGP + Traceroute
    Probe Firmware + DNS Performance

Author
------
Helen Liu
============================================================
"""


# ==========================================================
# Supported Observation Types
# ==========================================================

SUPPORTED_OBSERVATION_TYPES = [
    "DNS",
    "PING",
    "TRACEROUTE",
    "BGP",
    "STREAMING",
    "SNMP",
]


# ==========================================================
# Canonical Observation Framework
#
# Purpose
# -------
# Defines the complete structure of one normalized network
# Observation.
#
# Core sections:
#
#     - identity
#     - metadata
#     - measurement
#     - probe
#     - network
#     - location
#     - status
#
# Capability sections:
#
#     - protocol
#     - routing
#     - path
#     - telemetry
#
# Analytics results are not stored inside Observation.
# ==========================================================

OBSERVATION_FRAMEWORK = {

    # ======================================================
    # Identity
    #
    # observation_id
    #     Generated by this platform.
    #
    # measurement_id
    #     RIPE Atlas Measurement identifier.
    #
    # probe_id
    #     RIPE Atlas Probe identifier.
    #
    # Example
    # -------
    # observation_id = "dns-186325158-1003350-1782991276"
    # measurement_id = 186325158
    # probe_id = 1003350
    # ======================================================

    "identity": [
        "observation_id",
        "measurement_id",
        "probe_id",
    ],

    # ======================================================
    # Metadata
    #
    # timestamp
    #     Time when the Observation was executed.
    #
    # stored_timestamp
    #     Time when the source platform stored the result.
    #
    # observation_type
    #     Canonical platform type, such as DNS or BGP.
    #
    # measurement_engine_version
    #     Runtime Measurement engine version.
    #     RIPE Atlas source key: mver
    #
    # probe_firmware_version
    #     Firmware version used when this specific result was
    #     generated.
    #     RIPE Atlas source key: fw
    #
    # The runtime firmware value is preserved separately from
    # probe.definition.firmware_version because the current
    # Probe inventory may have changed since the Observation.
    # ======================================================

    "metadata": [
        "timestamp",
        "stored_timestamp",
        "observation_type",
        "measurement_engine_version",
        "probe_firmware_version",
    ],

    # ======================================================
    # Measurement
    #
    # Stores the definition associated with the Observation.
    #
    # The following source URL fields are intentionally not
    # included:
    #
    #     group
    #     result
    #
    # group_id is retained as the stable identifier.
    #
    # Result fields that duplicate Measurement metadata are
    # also excluded:
    #
    #     result.name
    #     result.msm_name
    #     result.group_id
    # ======================================================

    "measurement": {

        # --------------------------------------------------
        # Definition
        #
        # Source mapping:
        #
        # description -> description
        # type        -> measurement_type
        # group_id    -> group_id
        # --------------------------------------------------

        "definition": [
            "description",
            "measurement_type",
            "group_id",
        ],

        # --------------------------------------------------
        # Schedule
        #
        # Source mapping:
        #
        # interval   -> interval_seconds
        # start_time -> start_time
        # timeout    -> timeout_ms
        # --------------------------------------------------

        "schedule": [
            "interval_seconds",
            "start_time",
            "timeout_ms",
        ],

        # --------------------------------------------------
        # Network Configuration
        #
        # Source mapping:
        #
        # af       -> ip_version
        # protocol -> transport_protocol
        # port     -> destination_port
        #
        # destination_port may be null in Measurement
        # metadata. Runtime Result data may provide dst_port.
        # --------------------------------------------------

        "network": [
            "ip_version",
            "transport_protocol",
            "destination_port",
        ],

        # --------------------------------------------------
        # DNS Definition
        #
        # Query configuration is shared by all Observations
        # produced by the same Measurement.
        #
        # Source mapping:
        #
        # query_argument -> query_name
        # query_type     -> query_type
        # query_class    -> query_class
        # --------------------------------------------------

        "dns": {
            "question": [
                "query_name",
                "query_type",
                "query_class",
            ],
        },

        # --------------------------------------------------
        # Target
        #
        # target_hostname
        #     Configured Measurement target hostname.
        #
        # target_ip
        #     Configured Measurement target IP.
        #
        # resolved_ips
        #     IP addresses resolved while preparing the
        #     Measurement.
        #
        # target_ip and resolved_ips are both retained so the
        # platform can identify differences between the
        # configured target and the resolved target set.
        #
        # target_asn and target_prefix are also represented in
        # routing.bgp.destination for routing correlation.
        # --------------------------------------------------

        "target": [
            "target_hostname",
            "target_ip",
            "resolved_ips",
            "target_asn",
            "target_prefix",
        ],

        # --------------------------------------------------
        # Probe Scheduling
        # --------------------------------------------------

        "probes": [
            "probes_requested",
            "probes_scheduled",
        ],

        # --------------------------------------------------
        # Measurement Status
        #
        # Source mapping:
        #
        # status.id   -> id
        # status.name -> name
        # --------------------------------------------------

        "status": [
            "id",
            "name",
        ],

        # --------------------------------------------------
        # DNS Measurement Options
        #
        # These fields were added during the Measurement JSON
        # review because they affect result interpretation.
        # --------------------------------------------------

        "options": [
            "include_abuf",
            "resolve_on_probe",
            "udp_payload_size",
        ],
    },

    # ======================================================
    # Probe
    #
    # Stores Probe inventory, lifecycle, role, and current
    # inventory status.
    #
    # Probe address, location, ASN, and prefix fields are not
    # duplicated here.
    #
    # They are distributed to:
    #
    #     network
    #     location
    #     routing.bgp.source
    #
    # Probe tags are intentionally excluded from V1 because
    # they are currently not consumed by normalization,
    # telemetry, validation, or analytics.
    # ======================================================

    "probe": {

        # --------------------------------------------------
        # Definition
        #
        # firmware_version is the version stored in current
        # Probe inventory.
        #
        # It is separate from:
        #
        # metadata.probe_firmware_version
        #
        # which records the firmware used for the specific
        # runtime Observation.
        # --------------------------------------------------

        "definition": [
            "probe_type",
            "description",
            "firmware_version",
            "is_anchor",
        ],

        # --------------------------------------------------
        # Lifecycle
        # --------------------------------------------------

        "lifecycle": [
            "first_connected",
            "last_connected",
            "total_uptime",
        ],

        # --------------------------------------------------
        # Probe Status
        #
        # Source mapping:
        #
        # status.id    -> id
        # status.name  -> name
        # status.since -> since
        #
        # status_since is retained separately because the
        # source JSON provides both an ISO timestamp and a
        # Unix timestamp.
        # --------------------------------------------------

        "status": [
            "id",
            "name",
            "since",
            "status_since",
        ],
    },

    # ======================================================
    # Network
    #
    # Stores protocol-independent runtime network facts.
    #
    # Canonical Source Address Decision
    # ---------------------------------
    # RIPE Atlas Result JSON may contain:
    #
    #     src_addr
    #     from
    #
    # src_addr may be an internal or private address.
    #
    # from normally matches the Probe public address.
    #
    # The canonical source address is taken from Probe
    # inventory address_v4/address_v6, or Result.from when
    # required.
    #
    # Result.src_addr is intentionally not retained in V1.
    #
    # Source IPv4 and IPv6 remain separate to preserve
    # address-family meaning.
    #
    # response_time_ms
    # ----------------
    # Complete transaction time reported by the source.
    #
    # For DNS it represents the elapsed time from sending the
    # query until receiving the corresponding response.
    #
    # It is not pure routing latency.
    # ======================================================

    "network": [
        "ip_version",
        "source_ipv4",
        "source_ipv6",
        "destination_ipv4",
        "destination_ipv6",
        "destination_port",
        "transport_protocol",
        "response_time_ms",
    ],

    # ======================================================
    # Location
    #
    # Contains geographic information only.
    #
    # ASN and network prefix values belong to Routing.
    #
    # GeoJSON coordinates are ordered:
    #
    #     [longitude, latitude]
    #
    # Source mapping:
    #
    # country_code            -> country
    # geometry.coordinates[0] -> longitude
    # geometry.coordinates[1] -> latitude
    # geometry.type           -> geometry_type
    # ======================================================

    "location": [
        "country",
        "latitude",
        "longitude",
        "geometry_type",
    ],

    # ======================================================
    # Protocol
    #
    # Stores the canonical decoded protocol object.
    #
    # All supported protocols share the same structure.
    # Protocol-specific fields are stored inside "decoded".
    # ======================================================

    "protocol": [
        "name",
        "display_name",
        "family",
        "version",
        "decoded",
    ],

    # ======================================================
    # Routing
    #
    # Stores routing information associated with the
    # Observation.
    #
    # DNS Observations currently use BGP inventory metadata:
    #
    #     source
    #         Probe ASN and Prefix
    #
    #     destination
    #         Measurement target ASN and Prefix
    #
    # IPv4 and IPv6 values remain separate.
    # ======================================================

    "routing": {

        "bgp": {

            # ----------------------------------------------
            # Source Routing Inventory
            #
            # Probe source mapping:
            #
            # asn_v4    -> asn_v4
            # asn_v6    -> asn_v6
            # prefix_v4 -> prefix_v4
            # prefix_v6 -> prefix_v6
            # ----------------------------------------------

            "source": [
                "asn_v4",
                "asn_v6",
                "prefix_v4",
                "prefix_v6",
            ],

            # ----------------------------------------------
            # Destination Routing Inventory
            #
            # Measurement source mapping:
            #
            # target_asn
            #     -> asn_v4 or asn_v6 according to af
            #
            # target_prefix
            #     -> prefix_v4 or prefix_v6 according to af
            # ----------------------------------------------

            "destination": [
                "asn_v4",
                "asn_v6",
                "prefix_v4",
                "prefix_v6",
            ],

            # ----------------------------------------------
            # BGP Path Attributes
            #
            # Reserved for BGP Observations collected from:
            #
            #     RouteViews
            #     RIPE RIS
            #     RIPE RIS Live
            #
            # DNS Observations normally leave these empty.
            # ----------------------------------------------

            "path_attributes": [
                "next_hop",
                "as_path",
                "local_preference",
                "med",
                "communities",
            ],
        },
    },

    # ======================================================
    # Path
    #
    # Stores normalized forwarding-path information.
    #
    # DNS Observations currently leave this capability empty.
    #
    # Traceroute Observations may populate it later.
    # ======================================================

    "path": {

        "traceroute": [
            "hop_count",
            "hop_list",
            "hop_ip",
            "hop_latency",
            "hop_as",
        ],
    },

    # ======================================================
    # Status
    #
    # Stores the normalized execution outcome of one
    # Observation.
    #
    # A dedicated status section allows successful and failed
    # Results to share the same Canonical Framework.
    #
    # Example failure categories:
    #
    #     timeout
    #     network_error
    #     dns_error
    #     malformed_packet
    #     empty_response
    #
    # DNS protocol response codes such as NXDOMAIN and
    # SERVFAIL may later be decoded from raw_abuf.
    #
    # They should not automatically be treated as transport
    # failures because a valid DNS response may contain an
    # error response code.
    # ======================================================

    "status": [
        "success",
        "code",
        "message",
    ],

    # ======================================================
    # Telemetry
    #
    # Stores platform collection and processing metadata.
    #
    # This section does not store DNS business metrics.
    #
    # Metrics such as:
    #
    #     response_time_ms
    #     packet_size
    #     answer_count
    #
    # are generated by the Go Telemetry Builder from their
    # canonical Observation sections.
    #
    # sampling_interval is normally copied from:
    #
    #     measurement.schedule.interval_seconds
    #
    # collection_time is the time when the local Collector
    # downloaded the source data.
    #
    # processing_time is the time when normalization created
    # the Observation.
    #
    # archive_time is the time when the Observation was
    # written to the local archive.
    #
    # Runtime RIPE Atlas values fw and mver are stored in
    # metadata rather than telemetry because they describe
    # the specific source execution environment.
    # ======================================================

    "telemetry": [
        "collector",
        "collector_version",
        "platform",
        "sampling_interval",
        "collection_time",
        "processing_time",
        "archive_time",
    ],
}


# ==========================================================
# Utility Functions
# ==========================================================

def get_supported_observation_types() -> list[str]:
    """
    Return all supported Observation types.

    Returns
    -------
    list[str]
        Independent copy of the supported Observation types.
    """

    return SUPPORTED_OBSERVATION_TYPES.copy()


def get_observation_framework() -> dict:
    """
    Return the Canonical Observation Framework.

    Returns
    -------
    dict
        Independent top-level copy of the Framework.

    Engineering Note
    ----------------
    This is a shallow copy.

    Nested dictionaries and lists remain shared with the
    original Framework definition.

    Use create_empty_observation() when a mutable Observation
    instance is required.
    """

    return OBSERVATION_FRAMEWORK.copy()


def get_core_sections() -> list[str]:
    """
    Return the core Observation section names.

    Returns
    -------
    list[str]
        Core section names.
    """

    return [
        "identity",
        "metadata",
        "measurement",
        "probe",
        "network",
        "location",
        "status",
    ]


def get_capability_sections() -> list[str]:
    """
    Return capability-based Observation section names.

    Returns
    -------
    list[str]
        Capability section names.
    """

    return [
        "protocol",
        "routing",
        "path",
        "telemetry",
    ]


# ==========================================================
# Observation Factory
# ==========================================================

def create_empty_observation() -> dict:
    """
    Create an empty Canonical Observation object.

    Purpose
    -------
    Creates a new Observation instance following the
    Canonical Observation Framework.

    Every call creates new mutable dictionaries and lists.

    Observation instances therefore do not share mutable
    state.

    Returns
    -------
    dict
        Empty Canonical Observation object.

    Example
    -------
    observation = create_empty_observation()

    observation["identity"]["measurement_id"] = 186325158

    observation["identity"]["probe_id"] = 1003350

    observation["metadata"]["timestamp"] = 1782991276

    observation["measurement"]["dns"]["question"][
        "query_name"
    ] = "2.pool.ntp.org."

    observation["network"]["response_time_ms"] = 46.505

    observation["protocol"]["dns"]["packet"][
        "raw_abuf"
    ] = "QG6FAAABAAQAAA..."
    """

    return {

        "identity": {},

        "metadata": {},

        "measurement": {

            "definition": {},

            "schedule": {},

            "network": {},

            "dns": {
                "question": {},
            },

            "target": {},

            "probes": {},

            "status": {},

            "options": {},
        },

        "probe": {

            "definition": {},

            "lifecycle": {},

            "status": {},
        },

        "network": {},

        "location": {},

        "protocol": {

            "name": None,

            "display_name": None,

            "family": None,

            "version": None,

            "decoded": {},
        },

        "routing": {

            "bgp": {

                "source": {},

                "destination": {},

                "path_attributes": {},
            },
        },

        "path": {

            "traceroute": {},
        },

        "status": {},

        "telemetry": {},
    }