"""
============================================================
Project : DNS Measurement Platform
Module  : observation.py

Description
-----------
Defines the Canonical Observation Framework used by the
Network Telemetry Platform.

Observation represents one complete normalized network
observation collected from any supported data source.

The framework is designed around network observation
dimensions instead of individual protocols.

Observation is shared by:

    - Collector
    - Parser
    - Normalizer
    - SQLite Archive
    - Telemetry Builder
    - InfluxDB
    - Grafana
    - Analytics Engine
    - AI Insight

Design Philosophy
-----------------
Observation is the canonical data model.

Observation should not depend on SQLite, InfluxDB, Grafana,
or any storage implementation.

Raw Data
    -> Parser
    -> Normalizer
    -> Observation
    -> SQLite Archive

Observation
    -> Telemetry Builder
    -> InfluxDB
    -> Grafana

Analytics correlates multiple observations, for example:

    DNS + BGP
    DNS + Traceroute
    DNS + Streaming Telemetry

Author
------
Helen Liu
============================================================
"""


# ==========================================================
# Supported Observation Types
#
# Purpose
# -------
# Defines the observation types supported by the platform.
#
# Example
# -------
# A DNS measurement from RIPE Atlas will use:
#
#     observation_type = "DNS"
#
# A RouteViews record will use:
#
#     observation_type = "BGP"
# ==========================================================

SUPPORTED_OBSERVATION_TYPES = [
    "DNS",
    "PING",
    "TRACEROUTE",
    "BGP",
    "STREAMING",
    "SNMP",
]


# ==========================================================
# Canonical Observation Framework
#
# Purpose
# -------
# Defines the complete structure of one normalized network
# observation.
#
# Core dimensions:
#     - identity
#     - metadata
#     - network
#     - address_family
#     - location
#
# Capability dimensions:
#     - protocol
#     - routing
#     - path
#     - telemetry
#
# Analytics is not part of Observation.
# ==========================================================

OBSERVATION_FRAMEWORK = {

    # ======================================================
    # Identity
    #
    # Purpose
    # -------
    # Stores platform-level identity fields.
    #
    # observation_id is generated by this platform.
    # measurement_id and probe_id usually come from RIPE Atlas.
    #
    # Example
    # -------
    # observation_id = "dns-180080176-65598-1781482173"
    # measurement_id = 180080176
    # probe_id = 65598
    # ======================================================

    "identity": [
        "observation_id",
        "measurement_id",
        "probe_id",
    ],

    # ======================================================
    # Metadata
    #
    # Purpose
    # -------
    # Stores general information describing one observation.
    #
    # Every observation must contain metadata.
    #
    # Example
    # -------
    # timestamp = 1781482173
    # observation_type = "DNS"
    # measurement_name = "Tdig"
    # ======================================================

    "metadata": [
        "timestamp",
        "stored_timestamp",
        "observation_type",
        "measurement_name",
    ],

    # ======================================================
    # Network
    #
    # Purpose
    # -------
    # Describes how the observation was collected at the
    # network / transport layer.
    #
    # Example
    # -------
    # resolver_ip = "4.2.2.1"
    # destination_port = 53
    # transport_protocol = "UDP"
    # response_time = 148.479
    # ======================================================

    "network": [
        "resolver_ip",
        "destination_port",
        "transport_protocol",
        "response_time",
    ],

    # ======================================================
    # Address Family
    #
    # Purpose
    # -------
    # Separates IPv4 and IPv6 information.
    #
    # IPv4 and IPv6 should not be mixed into the same field.
    #
    # Example
    # -------
    # ip_version = 4
    # source_ipv4 = "192.168.129.109"
    # destination_ipv4 = "4.2.2.1"
    #
    # ip_version = 6
    # source_ipv6 = "2001:db8::10"
    # destination_ipv6 = "2001:4860:4860::8888"
    # ======================================================

    "address_family": [
        "ip_version",
        "source_ipv4",
        "source_ipv6",
        "destination_ipv4",
        "destination_ipv6",
        "public_source_ip",
    ],

    # ======================================================
    # Location
    #
    # Purpose
    # -------
    # Describes where the observation originated.
    #
    # Usually populated from RIPE Atlas Probe Metadata.
    #
    # Example
    # -------
    # asn = 30997
    # country = "GH"
    # latitude = 5.6037
    # longitude = -0.1870
    # ======================================================

    "location": [
        "asn",
        "country",
        "latitude",
        "longitude",
        "probe_description",
    ],

    # ======================================================
# ======================================================
# Protocol
#
# Purpose
# -------
# Stores protocol-specific observation data.
#
# Each supported network protocol defines its own
# observation model while sharing the same Observation
# Framework.
#
# Only the protocol matching the current observation_type
# is populated.
#
# DNS Observation Model
# ---------------------
# Mirrors the structure of a DNS message defined in RFC 1035.
#
# DNS Message
#
#     Header
#         transaction_id
#         flags
#         opcode
#         rcode
#
#     Question
#         query_name
#         query_type
#         query_class
#
#     Answer
#         answer_count
#         answers
#         ttl
#
#     Authority
#         authority_count
#         authority
#
#     Additional
#         additional_count
#         additional
#
#     Raw Packet
#         packet_size
#         raw_abuf
#
# Example
# -------
# DNS
#
#     query_name = "youtube.com"
#
#     query_type = "A"
#
#     rcode = "NOERROR"
#
#     answers = [
#         "142.251.29.136",
#         "142.251.29.190"
#     ]
#
# Traceroute
#
#     hop_count = 12
#
#     hop_list = [...]
#
# BGP
#
#     prefix = "142.251.29.0/24"
#
#     origin_as = 15169
#
# Design Principle
# ----------------
# The Observation Framework stores protocol-independent
# metadata while preserving each protocol's native data
# structure whenever possible.
# ======================================================
    # ======================================================

"protocol": {

    "DNS": [

        # ----------------------------
        # DNS Header
        # ----------------------------
        "transaction_id",
        "flags",
        "opcode",
        "rcode",

        # ----------------------------
        # DNS Question
        # ----------------------------
        "query_name",
        "query_type",
        "query_class",

        # ----------------------------
        # DNS Answer
        # ----------------------------
        "answer_count",
        "answers",
        "ttl",

        # ----------------------------
        # DNS Authority
        # ----------------------------
        "authority_count",
        "authority",

        # ----------------------------
        # DNS Additional
        # ----------------------------
        "additional_count",
        "additional",

        # ----------------------------
        # Raw DNS Packet
        # ----------------------------
        "packet_size",
        "raw_abuf",
    ],

    "PING": [
        "packet_size",
        "packet_loss",
        "rtt",
    ],

    "TRACEROUTE": [
        "hop_count",
        "hop_list",
        "latency_per_hop",
    ],

    "BGP": [
        "prefix",
        "origin_as",
        "next_hop",
        "as_path",
        "communities",
    ],

    "STREAMING": [
        "interface",
        "cpu",
        "memory",
        "if_in_octets",
        "if_out_octets",
    ],

    "SNMP": [
        "oid",
        "value",
    ],
},
    # ======================================================
    # Routing
    #
    # Purpose
    # -------
    # Stores normalized routing information.
    #
    # Routing data may originate from RouteViews, RIPE RIS Live,
    # BGP collectors, or be derived from returned IP prefixes.
    #
    # This section is used for cross-observation correlation.
    #
    # Example
    # -------
    # returned_ip = "142.251.29.136"
    # prefix = "142.251.29.0/24"
    # origin_as = 15169
    # as_path = [30997, 3356, 15169]
    # ======================================================

    "routing": [
        "prefix",
        "origin_as",
        "next_hop",
        "as_path",
        "local_preference",
        "med",
        "communities",
    ],

    # ======================================================
    # Path
    #
    # Purpose
    # -------
    # Stores normalized forwarding path information.
    #
    # Usually populated by Traceroute observations.
    #
    # Can be correlated with routing and DNS observations.
    #
    # Example
    # -------
    # hop_count = 12
    # hop_ip = ["192.168.1.1", "10.0.0.1", "..."]
    # hop_latency = [2.1, 15.4, 42.8]
    # hop_as = [None, 3356, 15169]
    # ======================================================

    "path": [
        "hop_count",
        "hop_list",
        "hop_ip",
        "hop_latency",
        "hop_as",
    ],

    # ======================================================
    # Telemetry
    #
    # Purpose
    # -------
    # Stores telemetry collection metadata.
    #
    # This section describes how the observation entered the
    # telemetry pipeline.
    #
    # Time-series metrics are generated from Observation and
    # written to InfluxDB by the Telemetry Builder.
    #
    # Example
    # -------
    # collector = "RIPE Atlas"
    # collector_version = "2.6.2"
    # platform = "RIPE Atlas"
    # sampling_interval = 900
    # collection_time = 1781482173
    # storage_timestamp = 1781482227
    # ======================================================

    "telemetry": [
        "collector",
        "collector_version",
        "platform",
        "sampling_interval",
        "collection_time",
        "storage_timestamp",
    ],
}


# ==========================================================
# Utility Functions
# ==========================================================

def get_supported_observation_types():
    """
    Return all supported observation types.
    """

    return SUPPORTED_OBSERVATION_TYPES.copy()


def get_observation_framework():
    """
    Return the complete canonical observation framework.
    """

    return OBSERVATION_FRAMEWORK.copy()


def get_core_sections():
    """
    Return the core observation sections.

    Core sections should exist for every observation type.
    """

    return [
        "identity",
        "metadata",
        "network",
        "address_family",
        "location",
    ]


def get_capability_sections():
    """
    Return capability-based observation sections.

    These sections may be populated depending on the
    observation type.
    """

    return [
        "protocol",
        "routing",
        "path",
        "telemetry",
    ]


def get_protocol_fields(observation_type):
    """
    Return protocol-specific fields for the given observation type.

    Parameters
    ----------
    observation_type : str
        Observation type such as DNS, PING, TRACEROUTE, BGP,
        STREAMING or SNMP.
    """

    observation_type = observation_type.upper()

    if observation_type not in SUPPORTED_OBSERVATION_TYPES:
        raise ValueError(f"Unsupported observation type: {observation_type}")

    return OBSERVATION_FRAMEWORK["protocol"].get(observation_type, []).copy()


# ==========================================================
# Observation Factory
# ==========================================================

def create_empty_observation():
    """
    Create an empty Observation object.

    Purpose
    -------
    Creates a new Observation instance following the
    Canonical Observation Framework.

    This function guarantees that every observation
    contains all required sections before being populated
    by the Normalizer.

    Returns
    -------
    dict
        Empty Observation object.

    Example
    -------
    observation = create_empty_observation()

    observation["metadata"]["timestamp"] = 1781482173
    observation["network"]["resolver_ip"] = "4.2.2.1"
    """

    return {

        "identity": {},

        "metadata": {},

        "network": {},

        "address_family": {},

        "location": {},

        "protocol": {},

        "routing": {},

        "path": {},

        "telemetry": {}

    }