"""
============================================================
Project : DNS Measurement Platform
Module  : identity_normalizer.py

Description
-----------
Normalizes the Identity section of the Canonical
Observation.

Identity uniquely identifies one Observation.

The Observation ID is generated by this platform and is
independent of any backend database.

Author
------
Helen Liu
============================================================
"""

from typing import Any


# ==========================================================
# Public API
# ==========================================================

def normalize_identity(
    measurement: dict[str, Any],
    probe: dict[str, Any],
    result: dict[str, Any],
) -> dict[str, Any]:
    """
    Normalize the Identity section of one Observation.
    """

    measurement_id = result.get(
        "msm_id",
        measurement.get("id"),
    )

    probe_id = result.get(
        "prb_id",
        probe.get("id"),
    )

    timestamp = result.get(
        "timestamp",
    )

    observation_id = _build_observation_id(
        observation_type="dns",
        measurement_id=measurement_id,
        probe_id=probe_id,
        timestamp=timestamp,
    )

    return {

        "observation_id": observation_id,

        "measurement_id": measurement_id,

        "probe_id": probe_id,
    }


# ==========================================================
# Private Functions
# ==========================================================

def _build_observation_id(
    observation_type: str,
    measurement_id: Any,
    probe_id: Any,
    timestamp: Any,
) -> str:
    """
    Build the platform-generated Observation ID.

    Example
    -------
    dns-186325158-1003350-1782991276
    """

    return (
        f"{observation_type.lower()}-"
        f"{measurement_id}-"
        f"{probe_id}-"
        f"{timestamp}"
    )